# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Seung-Woo Jin, Ph.D.
title: Postdoctoral Research Associate
email: mi797912@snu.ac.kr
website: https://seungwoo-jin.github.io/

# Social links
github_username: Seungwoo-Jin
twitter_username: SeungWooJin2
orcid_username : Seung-Woo Jin
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: seung-woo-jin-a5079213b
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  Hello, I am a neuroscience researcher and currently a postdoctoral research fellow at Seoul National University. My research interest is how emotion modulates the cognition system, especially for learning and memory. 
  During my doctoral training, I focused on how place cells along the longitudinal axis of the hippocampus differentially process place and value information. 
  
  [*Curriculum Vitae*](https://drive.google.com/file/d/1Wm2OcrFwRr9q-q4mRxP0E6mAs9mlBT04/view?usp=sharing)


#연락처 : 010 - 3219 - 0466

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# test Section
# test_title: test

# More Section
#more_title: 그 밖에 활동
#more_content: | # this will include new lines to allow paragraphs
#  - [개인 블로그](https://pro-dev.tistory.com/)

# Footer
footer_show_references: true

# Build settings
livereload: true

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - Seung-Woo Jin-tag
